# Generated by Django 5.1.1 on 2025-07-04 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('booth_type', models.CharField(choices=[('Single', 'Single'), ('Group', 'Group')], max_length=10)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('08:00 - 10:00', '08:00 - 10:00'), ('10:00 - 12:00', '10:00 - 12:00'), ('12:00 - 14:00', '12:00 - 14:00'), ('14:00 - 16:00', '14:00 - 16:00'), ('16:00 - 18:00', '16:00 - 18:00')], max_length=20)),
                ('floor', models.CharField(choices=[('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor')], max_length=20)),
                ('booth_number', models.IntegerField(choices=[(1, 'Booth 1'), (2, 'Booth 2'), (3, 'Booth 3'), (4, 'Booth 4'), (5, 'Booth 5'), (6, 'Booth 6'), (7, 'Booth 7'), (8, 'Booth 8'), (9, 'Booth 9'), (10, 'Booth 10'), (11, 'Booth 11'), (12, 'Booth 12'), (13, 'Booth 13'), (14, 'Booth 14'), (15, 'Booth 15'), (16, 'Booth 16'), (17, 'Booth 17'), (18, 'Booth 18'), (19, 'Booth 19'), (20, 'Booth 20')])),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
