# Generated by Django 5.1.4 on 2025-06-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('booth_type', models.CharField(choices=[('Single', 'Single'), ('Group', 'Group')], max_length=10)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('08:00 - 10:00', '08:00 - 10:00'), ('10:00 - 12:00', '10:00 - 12:00'), ('12:00 - 14:00', '12:00 - 14:00'), ('14:00 - 16:00', '14:00 - 16:00'), ('16:00 - 18:00', '16:00 - 18:00')], max_length=20)),
                ('floor', models.CharField(choices=[('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor')], max_length=20)),
                ('booth_number', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boothbooking',
            name='booth_type',
        ),
        migrations.RemoveField(
            model_name='boothbooking',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='boothbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='BoothType',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='BoothBooking',
        ),
    ]
