# Generated by Django 5.1.4 on 2025-06-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0003_booth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='booth_number',
            field=models.IntegerField(choices=[(1, 'Booth 1'), (2, 'Booth 2'), (3, 'Booth 3'), (4, 'Booth 4'), (5, 'Booth 5'), (6, 'Booth 6'), (7, 'Booth 7'), (8, 'Booth 8'), (9, 'Booth 9'), (10, 'Booth 10'), (11, 'Booth 11'), (12, 'Booth 12'), (13, 'Booth 13'), (14, 'Booth 14'), (15, 'Booth 15'), (16, 'Booth 16'), (17, 'Booth 17'), (18, 'Booth 18'), (19, 'Booth 19'), (20, 'Booth 20')]),
        ),
    ]
