# Generated by Django 5.1.4 on 2025-06-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0004_alter_booth_booth_number'),
    ]

    operations = [
    ]
